services:
  nginx:
    depends_on:
    - superset
    image: nginx:mainline-alpine-slim
    ports:
    - 443:443
    - 80:80
    volumes:
    - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ${PWD}/nginx/conf.d:/etc/nginx/conf.d
    - ${PWD}/letsencrypt/certs/:/etc/letsencrypt
  superset:
    image: ducluongvn/superset_pck
version: '1.0'
