version: "1.0"

services:
  nginx:
    image: nginx:mainline-alpine-slim
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/letsencrypt/certs/:/etc/letsencrypt
    ports:
      - 443:443
      - 80:80

    depends_on:
      - superset

  superset:
    image: ducluongvn/superset_pck

  superset_pdt:
    image: ghcr.io/luongnguyentrong/lvtn_superset/pdt:master
