services:
  nginx:
    depends_on:
      - superset
    image: nginx:mainline-alpine-slim
    ports:
      - 443:443
      - 80:80
    volumes:
      - ${PWD}/nginx/:/etc/nginx/
      - ${PWD}/letsencrypt/certs/:/etc/letsencrypt
  superset:
    image: ducluongvn/superset_pck
version: '1.0'
