services:
  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:/letsencrypt
      - ${PWD}/certs:/etc/letsencrypt

  nginx:
    image: nginx
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}:/letsencrypt
      - ${PWD}/certs:/etc/letsencrypt

    ports:
      - 80:80
      - 443:443
